samplesite/authapp/urls.py
from django.urls import path

from authapp.views import login, logout

app_name = 'authapp'

urlpatterns = [
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
]

samplesite/bboard/urls.py
from django.urls import path, re_path
from bboard.views import index, by_rubric, BbCreateView

# app_name = 'bboard'

# urlpatterns = [
#     path('', index, name='index'),
#     path('<int:rubric_id>/', by_rubric, name='by_rubric'),
#     path('add/', BbCreateView.as_view(), name='add'),
# ]

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^(?P<rubric_id>[0-9]*)/$', by_rubric, name='by_rubric'),
    re_path(r'^add/$', BbCreateView.as_view(), name='add'),
]

samplesite/samplesite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('bboard.urls')),
    path('admin/', admin.site.urls),
]

samplesite/authapp/models.py
from django.db import models

# Create your models here.

samplesite/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm
from djangp.contrib.auth.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

samplesite/authapp/views.py
from django.contrib import auth
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from authapp.forms import UserLoginForm


def login(request):
    title = "вход"
    login_form = UserLoginForm(data=request.POST)

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse('index'))

    context = {
        'tiitle': title,
        'login_form': login_form,
    }

    return render(request, 'authapp/login.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

samplesite/templates/authapp/login.html
{% extends "layout/basic.html" %}

{% block content %}

    {% if user.is_authenticated %}
    <h3>
        <a href="{% url 'authapp:logout' %}">
            Выйти ({{ user.username }})
        </a>
    </h3>
    {% else %}
    <h3>
        <a href="{% url 'authapp:login' %}">
            Войти
        </a>
    </h3>
    {% endif %}

{% for bb in bbs %}
<div>
    <h2>{{ bb.title }}</h2>
    <p>{{ bb.content }}</p>
    <p>
        <a href="{% url 'by_rubric' bb.rubric.pk %}">
            {{ bb.rubric.name }}
        </a>
    </p>
    <p>{{ bb.published|date:"d.m.Y H:i:s" }}</p>
</div>
{% endfor %}
{% endblock %}